### ISSUE TITLE
Destroyed Git history and missing important fixes 

### ISSUE THREAD

**Issue by stravid** [bartsqueezy/ember-handlebars-brunch#1]
Hi, as a contributor of https://github.com/icholy/ember-handlebars-brunch I'm confused to see this repository.

First of all, why is the entire Git history gone? And secondly, there is already a maintained fork https://github.com/stravid/ember-handlebars-brunch and NPM package people use. This repository is also missing some crucial fixes like no module and Windows support.

I'm curious about your intentions and hope we can focus our work so people have one place to go.

Cheers,
David

**Comment by bartsqueezy** [comment]
The purpose of this repo will be to continue the maintenance and support of [the original ember-handlebars-brunch project](https://github.com/saiwong/ember-handlebars-brunch).  Considering that this project has been classified as "no longer supported" and based on conversation I've had with both original authors, I've created a new repo to centralize new development and bug fixes.  Important fixes from subsequent forks of the original project have been merged in and all previous contributors (including the original authors) have been given proper credit.  Licensing information has also been posted so developers can use this project within a business environment.  You have been added as a collaborator on this project as well.  Please feel free to merge any PRs that contain additional fixes.  If you would like to update the NPM registry and have your package point to this repo, that would be great.  Otherwise I can create an new one.  Let me know if you have any additional questions.  Thanks!

**Comment by stravid** [comment]
Thanks for your clarification, I will add a notice to my fork that this repository is maintained. Do you have a NPM account so I can add you as a maintainer?

**Comment by bartsqueezy** [comment]
No problem.  My NPM account name is "bartsqueezy".  Are you going to keep your NPM package pointed at your fork or redirect it's URL to this new repo?

**Comment by stravid** [comment]
I will redirect it for sure, no point in having two repositories for the same thing :-)

**Comment by stravid** [comment]
I finally had time to add you to NPM and I also published 1.0.4 :-)

**Comment by bartsqueezy** [comment]
Awesome!  I'll update the README.md to include proper instructions for using NPM to install this plugin for Brunch projects.  Thanks again for your help David!

Also, friendly reminder, I added you as a contributor on this project.  Feel free to update and help out on fixes if you have the time :)
